services:
  authlogin:
    build: ./auth-login
    env_file: .env
    image: leviathan119/authlogin:latest
    ports:
      - "5030:5030"
    restart: unless-stopped

  authrol:
    build: ./auth-rol
    env_file: .env
    image: leviathan119/authrol:latest
    ports:
      - "5032:5032"
    restart: unless-stopped

  authhash:
    build: ./auth-hash
    env_file: .env
    image: leviathan119/authhash:latest
    ports:
      - "5031:5031"
    restart: unless-stopped

  authtoken:
    build: ./auth-token
    env_file: .env
    image: leviathan119/authtoken:latest
    ports:
      - "5033:5033"
    restart: unless-stopped

